### PR TITLE
compatibility fixes for 4.8 and 4.9 toolchains.

### PR DESCRIPTION
**Pull request by k2wl**
this will fix compatibility issue with 4.8 and 4.9 toolchains while compiling.

### CODE REVIEW

**Comment by Quarx2k** [comment]
Not sure about new schedulers and governors

**Comment by k2wl** [comment]
testing the schedules and governers ..so far working good.

**Comment by k2wl** [comment]
sir please close the pull request...
my mistake add those governerrs and i/o's.
will add them one by one. after proper testing. your work is great..!!!
keep it up.
thanks!!!

**Comment by Quarx2k** [comment]
Np, i can manually cherry-pick fixes for gcc:)

**Pull request closed without merging**
